name: Holograms
version: '${version}'
main: tech.blastmc.holograms.Holograms
api-version: 1.21
permissions:
  holograms:
    default: op
  holograms.*:
    description: Allows all commands for editing holograms
    default: op
    children:
      holograms.create: true
      holograms.delete: true
      holograms.list: true
      holograms.edit: true
      holograms.teleportTo: true
      holograms.moveHere: true
  holograms.create:
    default: op
  holograms.delete:
    default: op
  holograms.list:
    default: op
  holograms.edit:
    default: op
  holograms.teleportTo:
    default: op
  holograms.moveHere:
    default: op
  holograms.shift:
    default: op
  holograms.convert:
    default: op